# Site basics
title: Tea With Data
description: Sharing the art of data with a cup of tea.
url: "https://carolinetwd.github.io" # no trailing slash
baseurl: "" # empty for user site; for project site use "/<repo>"

# Author
author:
name: Caroline
email: talkwith.caroline@teawithdata.com

# Theme (use GH Pages’ default or minima)
theme: minima
show_excerpts: true  # works with minima to show post excerpts