# Site basics
title: Tea With Data
description: Sharing the art of data with a cup of tea.
url: "https://carolinetwd.github.io" # no trailing slash
baseurl: "" # empty for user site; for project site use "/<repo>"

# Author
author:
name: Caroline
email: talkwith.caroline@teawithdata.com

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one